name: Patmos CI Nix

on:
  push:
    branches: '**'
    paths-ignore:
      # Ignore Markdown file changes, as they are just docs
      # You can add more if you want, just be careful
      - '**.md'
  pull_request:
  schedule:
    # Run every monday at 1:00 AM
    - cron: '00 1 * * MON'

jobs:
  # https://nix.dev/guides/recipes/continuous-integration-github-actions
  cachix:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: ubuntu-latest
            system: x86_64-linux
            cc: clang
            cxx: clang++
          - platform: macos-latest
            system: aarch64-darwin
            cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - uses: cachix/cachix-action@v17
        with:
          name: patmos-llvm
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake show --show-trace --accept-flake-config
      - run: sudo nix eval --raw github:Kodalem/llvm-project/patmos-llvm-22x-rusty#packages.x86_64-linux.patmos-prefixed.outPath --accept-flake-config
      - run: nix build --no-link --print-out-paths github:Kodalem/llvm-project/patmos-llvm-22x-rusty#patmos-prefixed | cachix push patmos-llvm



